apiVersion: apps/v1
kind: Deployment
metadata:
  name: admissioncontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admissioncontroller
  template:
    metadata:
      labels:
        app: admissioncontroller
    spec:
      containers:
      - name: admissioncontroller
        image: nkeskar/admissioncontroller:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

