apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: admissioncontroller
webhooks:
  - name: admissioncontroller.default.svc
    rules:
        - apiGroups:   [""]
          apiVersions: ["v1"]
          operations: ["CREATE"]
          resources: ["pods"]
    clientConfig:
      service:
        namespace: default
        name: admissioncontroller
        path: /validate
      caBundle: <CA_BUNDLE>
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5